### ISSUE TITLE
generator can not distinguish between maven or gradle based applications

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster-docker-compose#10]
when any application in the subdirectories was built by gradle rather then with maven, the generator fails to find the correct docker directory

**Comment by deepu105** [comment]
Yes there is no gradle support yet

**Comment by jdubois** [comment]
Well, there's a Gradle plugin to build a Docker image, but I don't know how
it works :-(
Le 17 mars 2016 2:10 AM, "Deepu K Sasidharan" notifications@github.com a
écrit :

> Yes there is no gradle support yet

**Comment by xetys** [comment]
Oh, so far I tested yesterday night the docker plugin works like a charm. For some tests I just copied the docker folder from build to target, which worked for the generator to work through

**Comment by PierreBesson** [comment]
@xetys I will add docker gradle support to the main generator.
[EDIT] PR done: https://github.com/jhipster/generator-jhipster/pull/3195

**Comment by jdubois** [comment]
@xetys can you tell me how you used it? I'm currently writing the documentation for v3 and it looks like you know it better than me!

**Comment by deepu105** [comment]
I think main generator already supports docker build. we just need to add
support in this generator

Thanks & Regards,
Deepu

**Comment by xetys** [comment]
yes, it already was working as i checked out yesterday evening. The command was "gradle buildDocker" or "gradle bootRepackage buildDocker", which is an equivalent to "mvn package docker:build"...it generates the same files, but in /build, not in /target

P.S.  @jdubois i've updated my github profile data, so you are able to contact me

**Comment by deepu105** [comment]
Ok so for us it should be `gradle bootRepackage buildDocker`

Thanks & Regards,
Deepu

**Comment by PierreBesson** [comment]
@xetys, thanks for pointing it out that the buildDocker task already existed @jdubois and I were mistaken.

**Comment by jdubois** [comment]
OK thanks I'll try it

**Comment by pascalgrimaud** [comment]
See my PR : https://github.com/jhipster/generator-jhipster/pull/3029
Maven and Gradle are supported both!
I followed the official guide : https://spring.io/guides/gs/spring-boot-docker/
