### ISSUE TITLE
Feature: update JWT secret keys to same in all apps

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster-docker-compose#4]
Currently we have to update the keys manually. It would be nice to do that while running this generator so that all keys are in sync

**Comment by wmarques** [comment]
If you run with the registry the keys should be sync as the registry sends his config, including JWT key, to the applications. But maybe you have to start the registry before the other applications.
I couldn't find a way to wait for registry complete startup before starting the other apps in docker.

**Comment by pascalgrimaud** [comment]
@wmarques : it's the main "issue", when using docker-compose :-)
Compose introduced depend_on but it's not enough...

**Comment by wmarques** [comment]
So maybe we should tell the user to start the registry by running `docker-compose up jhipster-registry` and then run `docker-compose up`?

**Comment by deepu105** [comment]
yes May be we should document it better. or find a way to start these in
sequence

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
imo, it's the best option, @wmarques

**Comment by wmarques** [comment]
Done [here](https://github.com/jhipster/generator-jhipster-docker-compose/commit/eb32d467be8a236604b837c54e42dc115dd02197)
