### ISSUE TITLE
Create and use official jhipster/jhipster-console

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster-docker-compose#8]
At the moment, we use this image : [pbesson/jhipster-console](https://hub.docker.com/r/pbesson/jhipster-console/) -> https://github.com/jhipster/generator-jhipster-docker-compose/blob/master/generators/app/templates/elk.yml#L18

@PierreBesson : is jhipster-console project ready to integrate the [JHipster organization](https://hub.docker.com/r/jhipster/) ? If yes, what is the main Dockerfile ?

**Comment by PierreBesson** [comment]
Yes it is just a matter of time before I create the official docker hub image. I just tested that it worked on my own account.

**Comment by PierreBesson** [comment]
Closing via https://github.com/jhipster/generator-jhipster-docker-compose/commit/9d9671a590a7b786ffcadfe477030a23f940ddca
